### ISSUE TITLE
Start/Stop Simulation

### ISSUE THREAD

**Issue by MahadJanjua** [DGovi/soen343house#22]
Make the start/stop simulation button exit the simulation on press.

**Comment by adrientremblay** [comment]
![image](https://user-images.githubusercontent.com/8109538/96512916-38c30580-122f-11eb-8e2e-9ef90d409ae3.png)

**Comment by adrientremblay** [comment]
![image](https://user-images.githubusercontent.com/8109538/96512951-45dff480-122f-11eb-9276-5bfb799fd8fb.png)
